"""Closed-class lists used as authorship features.

Function words are weakly coupled to topic and strongly coupled to habit,
which is why they remain the workhorse of classical stylometry (Mosteller
and Wallace; Burrows). The lists below are short, English-only, and frozen
so exam walkthroughs stay reproducible.
"""

from __future__ import annotations

FUNCTION_WORDS: tuple[str, ...] = (
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "has",
    "have",
    "he",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "itself",
    "just",
    "me",
    "might",
    "more",
    "most",
    "must",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "now",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "she",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "will",
    "with",
    "would",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
)

FUNCTION_WORD_SET = frozenset(FUNCTION_WORDS)

FIRST_PERSON_SINGULAR = frozenset({"i", "me", "my", "mine", "myself"})
FIRST_PERSON_PLURAL = frozenset({"we", "us", "our", "ours", "ourselves"})
SECOND_PERSON = frozenset({"you", "your", "yours", "yourself", "yourselves"})
HEDGE_MARKERS = frozenset(
    {
        "maybe",
        "perhaps",
        "possibly",
        "probably",
        "seems",
        "seem",
        "appear",
        "appears",
        "generally",
        "often",
        "usually",
        "somewhat",
        "rather",
        "quite",
    }
)
NOMINALIZATION_SUFFIXES = ("tion", "sion", "ment", "ness", "ity", "ance", "ence")

PUNCT_COUNTS = (
    ("comma", ","),
    ("period", "."),
    ("semicolon", ";"),
    ("colon", ":"),
    ("exclaim", "!"),
    ("question", "?"),
    ("quote", '"'),
    ("dash", "—"),
    ("hyphen", "-"),
    ("paren", "("),
)
