"""Closed-class lists used as style, not topic.

Function words are high-frequency and relatively topic-invariant. That
is why exam answers should prefer them over content nouns when the
question is about *authorship* rather than *subject*.
"""

from __future__ import annotations

# A compact English function-word inventory. Order is part of the
# feature schema: vector index i is always FUNCTION_WORDS[i].
FUNCTION_WORDS: tuple[str, ...] = (
    "a",
    "about",
    "after",
    "all",
    "also",
    "an",
    "and",
    "any",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "between",
    "both",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "down",
    "each",
    "for",
    "from",
    "had",
    "has",
    "have",
    "her",
    "here",
    "him",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "like",
    "may",
    "me",
    "might",
    "more",
    "most",
    "my",
    "no",
    "not",
    "now",
    "of",
    "on",
    "one",
    "only",
    "or",
    "other",
    "our",
    "out",
    "over",
    "own",
    "same",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "up",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "will",
    "with",
    "would",
    "you",
    "your",
)

PRONOUNS = frozenset(
    {
        "i",
        "me",
        "my",
        "mine",
        "myself",
        "we",
        "us",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
    }
)

MODALS = frozenset(
    {
        "can",
        "could",
        "may",
        "might",
        "must",
        "shall",
        "should",
        "will",
        "would",
        "ought",
    }
)

HEDGES = frozenset(
    {
        "almost",
        "apparently",
        "arguably",
        "basically",
        "fairly",
        "generally",
        "kinda",
        "maybe",
        "perhaps",
        "possibly",
        "probably",
        "quite",
        "rather",
        "seemingly",
        "somewhat",
        "sorta",
        "usually",
    }
)

FIRST_PERSON = frozenset({"i", "me", "my", "mine", "myself", "we", "us", "our", "ours"})
SECOND_PERSON = frozenset({"you", "your", "yours", "yourself", "yourselves"})

CONTRACTIONS = frozenset(
    {
        "aren't",
        "can't",
        "couldn't",
        "didn't",
        "doesn't",
        "don't",
        "hadn't",
        "hasn't",
        "haven't",
        "he'd",
        "he'll",
        "he's",
        "i'd",
        "i'll",
        "i'm",
        "i've",
        "isn't",
        "it's",
        "let's",
        "mightn't",
        "mustn't",
        "she'd",
        "she'll",
        "she's",
        "shouldn't",
        "that's",
        "there's",
        "they'd",
        "they'll",
        "they're",
        "they've",
        "wasn't",
        "we'd",
        "we'll",
        "we're",
        "we've",
        "weren't",
        "what's",
        "won't",
        "wouldn't",
        "you'd",
        "you'll",
        "you're",
        "you've",
    }
)


def function_word_index() -> dict[str, int]:
    return {word: i for i, word in enumerate(FUNCTION_WORDS)}
