"""Closed-class lists used as style features.

These are public-domain function words and a few register flags. They are
not a trained vocabulary and they are not scraped from any shared task.
"""

from __future__ import annotations

FUNCTION_WORDS: tuple[str, ...] = (
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "almost",
    "along",
    "already",
    "also",
    "although",
    "always",
    "am",
    "among",
    "amongst",
    "an",
    "and",
    "another",
    "any",
    "are",
    "around",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "doing",
    "down",
    "during",
    "each",
    "either",
    "enough",
    "even",
    "ever",
    "every",
    "few",
    "for",
    "from",
    "further",
    "had",
    "has",
    "have",
    "having",
    "he",
    "hence",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "however",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "itself",
    "just",
    "least",
    "less",
    "like",
    "many",
    "may",
    "me",
    "might",
    "more",
    "moreover",
    "most",
    "much",
    "must",
    "my",
    "myself",
    "neither",
    "never",
    "nevertheless",
    "no",
    "nor",
    "not",
    "now",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "quite",
    "rather",
    "same",
    "shall",
    "she",
    "should",
    "since",
    "so",
    "some",
    "still",
    "such",
    "than",
    "that",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "therefore",
    "these",
    "they",
    "this",
    "those",
    "though",
    "through",
    "thus",
    "to",
    "too",
    "toward",
    "towards",
    "under",
    "until",
    "up",
    "upon",
    "us",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "whether",
    "which",
    "while",
    "whilst",
    "who",
    "whom",
    "whose",
    "why",
    "will",
    "with",
    "within",
    "without",
    "would",
    "yet",
    "you",
    "your",
    "yours",
    "yourself",
)

FUNCTION_INDEX = {w: i for i, w in enumerate(FUNCTION_WORDS)}

HEDGES: frozenset[str] = frozenset(
    {
        "accordingly",
        "apparently",
        "arguably",
        "fairly",
        "hence",
        "however",
        "maybe",
        "moreover",
        "nevertheless",
        "perhaps",
        "presumably",
        "quite",
        "rather",
        "relatively",
        "seemingly",
        "somewhat",
        "subsequently",
        "therefore",
        "thus",
    }
)

FIRST_PERSON: frozenset[str] = frozenset(
    {"i", "me", "my", "mine", "myself"}
)
SECOND_PERSON: frozenset[str] = frozenset(
    {"you", "your", "yours", "yourself", "yourselves"}
)
INCLUSIVE_WE: frozenset[str] = frozenset(
    {"we", "us", "our", "ours", "ourselves"}
)

CONTRACTION_MARKERS: tuple[str, ...] = (
    "n't",
    "'ll",
    "'re",
    "'ve",
    "'d",
    "'m",
)

PASSIVE_AUX: frozenset[str] = frozenset({"was", "were", "been", "being", "is", "are"})

SHALL_MUST: frozenset[str] = frozenset({"shall", "must"})
VOCATIVES: frozenset[str] = frozenset(
    {"dearest", "dear", "hey", "yo", "hi", "hello", "ok", "okay"}
)

INFORMAL: frozenset[str] = frozenset(
    {
        "gonna",
        "wanna",
        "kinda",
        "sorta",
        "yeah",
        "ok",
        "okay",
        "lol",
        "btw",
        "imo",
        "anyway",
        "anyways",
    }
)
