"""Closed-class lists for the exam formula card.

These are teaching lists, not a claim about the whole language. Count
them with a pencil on a six-sentence document and you should match
``inkfold explain``.
"""

from __future__ import annotations

# Function words: topic-light closed class used for Burrows-style Delta
# and for a smoothed cosine. Keep this list stable; labs cite the length.
FUNCTION_WORDS: tuple[str, ...] = (
    "a",
    "about",
    "after",
    "all",
    "also",
    "an",
    "and",
    "any",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "between",
    "both",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "down",
    "each",
    "even",
    "every",
    "for",
    "from",
    "had",
    "has",
    "have",
    "her",
    "here",
    "hers",
    "him",
    "his",
    "how",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "like",
    "may",
    "more",
    "most",
    "must",
    "my",
    "no",
    "nor",
    "not",
    "now",
    "of",
    "on",
    "once",
    "only",
    "or",
    "other",
    "our",
    "out",
    "over",
    "own",
    "same",
    "shall",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "will",
    "with",
    "would",
    "yet",
    "you",
    "your",
)

FUNCTION_WORD_INDEX = {w: i for i, w in enumerate(FUNCTION_WORDS)}

FIRST_PERSON = frozenset(
    {
        "i",
        "i'd",
        "i'll",
        "i'm",
        "i've",
        "me",
        "mine",
        "my",
        "myself",
    }
)

WE_PERSON = frozenset({"we", "we'd", "we'll", "we're", "we've", "us", "our", "ours", "ourselves"})

SECOND_PERSON = frozenset(
    {
        "you",
        "you'd",
        "you'll",
        "you're",
        "you've",
        "your",
        "yours",
        "yourself",
        "yourselves",
    }
)

CONTRACTIONS = frozenset(
    {
        "ain't",
        "aren't",
        "can't",
        "couldn't",
        "didn't",
        "doesn't",
        "don't",
        "gonna",
        "hadn't",
        "hasn't",
        "haven't",
        "he'd",
        "he'll",
        "he's",
        "how'd",
        "i'd",
        "i'll",
        "i'm",
        "i've",
        "isn't",
        "it'd",
        "it'll",
        "it's",
        "let's",
        "she'd",
        "she'll",
        "she's",
        "shouldn't",
        "that's",
        "there's",
        "they'd",
        "they'll",
        "they're",
        "they've",
        "wasn't",
        "we'd",
        "we'll",
        "we're",
        "we've",
        "weren't",
        "what's",
        "won't",
        "wouldn't",
        "y'all",
        "you'd",
        "you'll",
        "you're",
        "you've",
    }
)

FORMAL = frozenset(
    {
        "accordingly",
        "aforesaid",
        "compliance",
        "hereby",
        "herein",
        "hereof",
        "hereto",
        "must",
        "prescribed",
        "pursuant",
        "shall",
        "thereof",
        "therein",
        "whereas",
        "whereof",
    }
)

HEDGES = frozenset(
    {
        "apparently",
        "appear",
        "appears",
        "approximately",
        "around",
        "fairly",
        "maybe",
        "perhaps",
        "possible",
        "possibly",
        "probably",
        "quite",
        "rather",
        "roughly",
        "seem",
        "seemed",
        "seems",
        "somewhat",
        "suggest",
        "suggested",
        "suggests",
        "likely",
        "consistent",
    }
)

# Informal vocatives and chat crumbs that show up in Stall / Wire.
VOCATIVES = frozenset(
    {
        "btw",
        "hey",
        "hi",
        "lol",
        "lmao",
        "mate",
        "ok",
        "okay",
        "pls",
        "please",
        "tho",
        "yeah",
        "yep",
        "yo",
    }
)

# Length of the function-word list, cited on the formula card.
N_FUNCTION_WORDS = len(FUNCTION_WORDS)
