"""Closed-class word lists used as style markers.

Function words are high-frequency and low-content. They are the classic
stylometric signal because authors reuse them unconsciously and they
survive topic changes better than nouns. The lists below are ordinary
English closed-class items, not a copyrighted resource.
"""

from __future__ import annotations

# Mosteller–Wallace / Burrows-style closed class, trimmed to words that
# actually appear in short modern paragraphs. Keep the order stable so
# feature indices stay comparable across documents.
FUNCTION_WORDS: tuple[str, ...] = (
    "a",
    "about",
    "after",
    "all",
    "also",
    "an",
    "and",
    "any",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "between",
    "both",
    "but",
    "by",
    "can",
    "could",
    "did",
    "do",
    "does",
    "down",
    "each",
    "even",
    "every",
    "for",
    "from",
    "had",
    "has",
    "have",
    "her",
    "here",
    "him",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "like",
    "may",
    "me",
    "more",
    "most",
    "my",
    "no",
    "not",
    "now",
    "of",
    "on",
    "one",
    "only",
    "or",
    "other",
    "our",
    "out",
    "over",
    "own",
    "same",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "up",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "why",
    "will",
    "with",
    "would",
    "you",
    "your",
)

CONTRACTIONS: tuple[str, ...] = (
    "aren't",
    "can't",
    "couldn't",
    "didn't",
    "doesn't",
    "don't",
    "hadn't",
    "hasn't",
    "haven't",
    "he'd",
    "he'll",
    "he's",
    "i'd",
    "i'll",
    "i'm",
    "i've",
    "isn't",
    "it's",
    "let's",
    "she'd",
    "she'll",
    "she's",
    "shouldn't",
    "that's",
    "there's",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "wasn't",
    "we'd",
    "we'll",
    "we're",
    "we've",
    "weren't",
    "what's",
    "won't",
    "wouldn't",
    "you'd",
    "you'll",
    "you're",
    "you've",
)

HEDGES: tuple[str, ...] = (
    "almost",
    "apparently",
    "approximately",
    "arguably",
    "around",
    "fairly",
    "maybe",
    "might",
    "perhaps",
    "possibly",
    "probably",
    "quite",
    "rather",
    "seemingly",
    "somewhat",
    "suggests",
)

INTENSIFIERS: tuple[str, ...] = (
    "extremely",
    "highly",
    "incredibly",
    "really",
    "so",
    "super",
    "totally",
    "very",
)

FIRST_PERSON: frozenset[str] = frozenset(
    {"i", "i'd", "i'll", "i'm", "i've", "me", "my", "mine", "myself", "we", "our", "ours", "us"}
)
SECOND_PERSON: frozenset[str] = frozenset(
    {"you", "you'd", "you'll", "you're", "you've", "your", "yours"}
)
IMPERSONAL: frozenset[str] = frozenset({"one", "one's"})

FUNCTION_WORD_INDEX: dict[str, int] = {
    word: index for index, word in enumerate(FUNCTION_WORDS)
}
